### ISSUE TITLE
Homepage revisions

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/GM-Website#29]

**Comment by luizakp** [comment]
@rodricastillo9013 just to make sure, this changes are not on figma yet right? no pressure hahahha

**Comment by rodricastillo9013** [comment]
no yet! hahaha, tomorrow yes ! sorry! :) @luizakp

**Comment by rodricastillo9013** [comment]
@luizakp luiza I've already made the changes, I'll write you privately to coordinate details! thanks
