### ISSUE TITLE
Projects pages need redesign

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/GM-Website#30]
https://www.generalmagic.io/projects

We need to better present the projects and organizations we work(ed) with.
I wouldn't structure the projects based on the individual work we did (i.e branding, ux etc.), rather present the project or org and tell a story on how we partner with them and what value we add to their organization, while also talking about a project.

Example:
Commons Stack
[short intro on how we support them]
Projects we did: Commons Simulator, Praise System, Trusted Seed Dashboard, Swag Shop

Giveth
[short intro on how we support them] mention that we're actively involved in the governance of the DAO.
We can show&tell the Giveth platform, GIVeconomy, NFTs, Swag Shop

TEC
[short intro on how we support them] contributed to the creation of the Commons
Projects: TEC Branding and Website, Commons Dashboard, ABC (Augmented Bonding Curve) Advanced Dashboard, NFTs, Swag Shop

TE Academy
[short intro on how we support them]
Project: TE Academy portal

ENS
[short intro on how we support them]
Projects: Swag Shop

clrFund
[short intro about them and how we support them]
Projects: QF DApp

DAppNode
[short intro about them and how we support them] we also used their smart contracts on other projects
Projects: General design support (LM app recently)

BrightID
[short intro about them and how we support them]
We helped them redefine BrightID DAO Conviction Voting parameters. https://forum.brightid.org/t/revisiting-the-brightdao-parameters-with-general-magic-support/355

Aragon
[short intro about them and how we support them] We joined their DAO Experts program. 
Project: TAO Voting Dashboard

Tokenlog
[short intro about the project and how we support it]
Project: Tokenlog V1 and V2

**Comment by rodricastillo9013** [comment]
Hi team! @anamarija09 @ahmadabugosh @divine-comedian @markoprljic  I need a little help with the definition of the content, anyone who wants to help me with this? So we first define the content, and then continue with the designs? I have created this File to work here. Thanks!
https://docs.google.com/document/d/1mj-JcfI1HDtM9BKP92h_1C3VSTRxv4YsX8uqt2xcd_M/edit?usp=sharing

**Comment by markoprljic** [comment]
@rodricastillo9013 Can you please move this doc to GM Drive folder and make it accessible to everyone? Thanks.

**Comment by rodricastillo9013** [comment]
https://docs.google.com/document/d/1mj-JcfI1HDtM9BKP92h_1C3VSTRxv4YsX8uqt2xcd_M/edit?usp=sharing Done!

**Comment by divine-comedian** [comment]
I added descriptions for all of the projects listed - mostly pulling verbatim or paraphrasing from their own content. 

I'm not familiar with the nature of all the relationships they have with GM but I wrote the ones I felt comfortable enough to explain.
