### ISSUE TITLE
About us revisions

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/GM-Website#31]
https://app.ruttl.com/share/RhBB1yE01Tk61iFpjIgl?page=YPiTAX3FfWpmfONTwNUf

See comments on the link above.

**Comment by rodricastillo9013** [comment]
ok! perfect! thanks

**Comment by rodricastillo9013** [comment]
@luizakp Done https://www.figma.com/file/wZXa6SD000KnRrLiOpQxm1/Web-Design?node-id=2121%3A7725
